### ISSUE TITLE
[BUG] useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by razzeee** [yanivam/react-svg-worldmap#112]
**Describe the bug** I'm getting a warning about the usage of useLayoutEffect

**To Reproduce** Steps to reproduce the behavior:

1. Clone https://github.com/flathub/frontend
2. Copy the production config from `.env.production` to `.env.development`
3. Run `yarn` then `yarn dev`
4. Goto http://localhost:3000/statistics
5. There should be an error in the terminal:
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at WorldMap (/home/razze/dev/frontend/node_modules/react-svg-worldmap/dist/index.js:16:13)
    at div
    at div
    at main
    at div
    at Main (webpack-internal:///./src/components/layout/Main.tsx:21:17)
    at Statistics (webpack-internal:///./pages/statistics.tsx:44:23)
    at UserInfoProvider (webpack-internal:///./src/context/user-info.tsx:24:29)
    at exports.ThemeProvider (/home/razze/dev/frontend/node_modules/next-themes/dist/index.js:1:1798)
    at MatomoProvider (/home/razze/dev/frontend/node_modules/@datapunt/matomo-tracker-react/lib/MatomoProvider.js:9:23)
    at App (webpack-internal:///./pages/_app.tsx:41:16)
    at I18nextProvider (/home/razze/dev/frontend/node_modules/react-i18next/dist/commonjs/I18nextProvider.js:13:19)
    at AppWithTranslation (/home/razze/dev/frontend/node_modules/next-i18next/dist/commonjs/appWithTranslation.js:91:22)
    at StyleRegistry (/home/razze/dev/frontend/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/home/razze/dev/frontend/node_modules/next/dist/server/render.js:415:29)
    at AppContainerWithIsomorphicFiberStructure (/home/razze/dev/frontend/node_modules/next/dist/server/render.js:447:57)
    at div
    at Body (/home/razze/dev/frontend/node_modules/next/dist/server/render.js:715:21)
```

**Expected behavior** 
No warning should happen

**Desktop (please complete the following information):**

- OS: Fedora 35
- Browser Firefox
- Version 98

**Comment by Josh-Cena** [comment]
Thanks for the report @razzeee Should be fixed by #113. Unfortunately I don't have publish access so you can't test the latest changes😞 Will have to wait for @yanivam to cut a new release
