### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'forwardRef')

### ISSUE THREAD

**Issue by devilchey** [yanivam/react-svg-worldmap#136]
Hello. When creating a simple example I get an error:

react.development.js:1282 Uncaught TypeError: Cannot read properties of undefined (reading 'forwardRef')
    at ./node_modules/react-svg-worldmap/dist/components/Region.js (Region.js:41:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/react-svg-worldmap/dist/index.js (index.js:22:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/views/statistics/Map.jsx (src_views_statistics_Statistic_js.chunk.js:15:76)
    at options.factory (react refresh:6:1)

can you help me?

**Comment by njtan142** [comment]
i have the same isue

**Comment by osaruagbonaye** [comment]
Same issue with next.js

**Comment by devilchey** [comment]
I use this

import Chart from 'react-google-charts'
<Chart chartType="GeoChart" data={visits} rootProps={{'data-testid': '1'}}/>

**Comment by sebastianbermea** [comment]
Same issue

**Comment by yanivam** [comment]
Hey @sebastianbermea, @devilchey, @osaruagbonaye, and @njtan142. The above error should be resolved in the latest version of the map on npm that I just posted. Can any of y'all check and close this issue? The issue was with the way React was imported. Thanks, Yams

**Comment by yanivam** [comment]
Closing this ticket for now, let me know if the issue persists
